### ISSUE TITLE
[Chore] Android CI 추가 설정

### ISSUE THREAD

**Issue by cwj-c** [THT-Team/THT-Android#8]
## 📪 Issue
Android CI 설정
## 📚 To-do
- [x] Slack Action CI 추가
- [x] Gradle Cache 추가
- [x] Build, lint를 병렬 작업으로 설정

**Comment by cwj-c** [comment]
**gradle build**는 **assembleDebug**, **assembleRelease**, **test**, **testDebugUnitTest**, **testReleaseUnitTest**를 포함하기에 **build**를 사용할것이라면 해당 **task**들을 사용하지 않는게 효율적
